jawaban quiz kalkulator mentor:

In [160]:
def calc(a,b,c):
    if(a.isnumeric()==True) and (c.isnumeric()==True):
        a = int(a)
        c = int(c)
        if b == 'x':
            print('hasil dari', a, b, c, ' adalah ', a*c)
        elif b == '+':
            print('hasil dari', a, b, c, ' adalah ', a+c)
        elif b == ':':
            print('hasil dari', a, b, c, ' adalah ', a/c)
        elif b == '-':
            print('hasil dari', a, b, c, ' adalah ', a-c)
        elif b == '^':
            print('hasil dari', a, b, c, ' adalah ', a**c)
        else:
            print('operator', b, 'tidak ditemukan')
    else:
        print('salah')

a = (input('masukkan angka1= '))
b = (input('masukkan operator= '))
c = (input('masukkan angka2= '))

calc(a,b,c)

masukkan angka1= 2
masukkan operator= +
masukkan angka2= 2
hasil dari 2 + 2  adalah  4


## NUMPY

array salah satu feature pada python seperti list yang berisi berbagai macam objek.

In [12]:
a = [1,2,3]

In [13]:
import numpy as np

one dimensional array

In [19]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [21]:
arr[3]

4

In [30]:
arr[2:]

array([3, 4])

In [31]:
arr.shape

(4,)

two dimensional array

consisting list of lists

In [27]:
lists = [[1,2,3], [4,5,6], [7,8,9]]

arr2 = np.array(lists)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2.shape #outputnya (baris, kolom)

(3, 3)

In [34]:
# np.zeros
print(np.zeros(8)) #one dimensional array
print(np.zeros([3,2])) #multi-dimensional array

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
# np.ones
print(np.ones(8)) #one dimensional array
print(np.ones([3,2])) #two dimensional array

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
# np.empty
np.empty(5)
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
# np.arange
print(np.arange(10))
print(np.arange(0,10,2)) #start,stop,step
print(np.arange(0,30,4)) #start,stop,step

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0  4  8 12 16 20 24 28]


In [52]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array([3,5,8,2,1,3,9,5,4])

print(np.append(c, [10,11]))
print(np.delete(c, [2,3]))
print(np.sort(d))

[ 1  2  3  4  5  6  7  8  9 10 11]
[1 2 5 6 7 8 9]
[1 2 3 3 4 5 5 8 9]


In [57]:
#ndim
print(c.ndim) #menampilkan jumlah dimensi dari suatu array
print(c.size)

print(c.reshape(3,3))

1
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
arr3 = np.array([[1,2,3,4]]) # dua kurung siku artinya dua dimensi (jadi matriks, udh ada baris)
print(arr3.shape) #outputnya 1 baris 4 kolom
print(arr3)

(1, 4)
[[1 2 3 4]]


In [61]:
# np.newaxis untuk nambah axis baru
arr4 = np.array([4,5,6])
arr4[np.newaxis]
print(arr4[:, np.newaxis].shape)

(3, 1)


In [65]:
arr7 = np.array([3,4,5,6,7,8,9])
arr8 = np.expand_dims(arr7, axis=1)
arr9 = np.expand_dims(arr7, axis=0)
print(arr8)
print(arr8.shape)
print(arr9)
print(arr9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


In [69]:
arr7 = np.array([3,4,5,6,7,8,9])
print(arr7*2)
print(arr7+2)

[ 6  8 10 12 14 16 18]
[ 5  6  7  8  9 10 11]


In [70]:
arr10 = np.array([[1,2,3], [4,5,6]])
print(arr10-4)

[[-3 -2 -1]
 [ 0  1  2]]


In [73]:
arr7 = np.array([3,4,5,6,7,8,9])
print(arr7[arr7>5])
print(arr7[arr7<=5])

[6 7 8 9]
[3 4 5]


In [77]:
arr11 = np.array([[3,5,7], [8,9,10], [-1, -2, -3]])
arr11.shape
print(arr11[arr11>5])

[ 7  8  9 10]


## QUIZ hourglass

belum selesai

In [98]:
tall = int(input('How tall? '))

if tall % 2 == 0:
    for i in range(tall-1):
        print(' ', end='')
    for k in range(tall-1):
        print('* ', end='')
for i in range(tall):
    print(' ' * (tall), end='')
    print('* '*(i+1))

How tall? 10
         * * * * * * * * *           * 
          * * 
          * * * 
          * * * * 
          * * * * * 
          * * * * * * 
          * * * * * * * 
          * * * * * * * * 
          * * * * * * * * * 
          * * * * * * * * * * 


In [102]:
arr0 = np.array([3,4,5,6,7])
arr78 = np.array([3,4,5,6,10])
print(np.vstack([arr0, arr78]))

[[ 3  4  5  6  7]
 [ 3  4  5  6 10]]


In [106]:
arr0 = np.array([3,4,5,6,7,8])
arr0_splt = np.hsplit(arr0,2)
(arr0_splt)

[array([3, 4, 5]), array([6, 7, 8])]

In [111]:
arr01 = np.array([[3,4,5,6],[7,8,9,10]])
print(arr01)
print(np.hsplit(arr01, 2))
print(np.vsplit(arr01, 2))

[[ 3  4  5  6]
 [ 7  8  9 10]]
[array([[3, 4],
       [7, 8]]), array([[ 5,  6],
       [ 9, 10]])]
[array([[3, 4, 5, 6]]), array([[ 7,  8,  9, 10]])]


operaasi aritmetik antar 2 array

In [121]:
arrayA=np.array([1,2,3])
arrayB = np.array([3,4,5])
print(arrayA+arrayB)
print(arrayA.sum())
print(arrayA.min())
print(arrayA.max())

[4 6 8]
6
1
3


In [118]:
arrayC=np.array([[1,2,3], [4,5,6]])
arrayD = np.array([[3,4,5], [6,7,8]])
print(arrayC-arrayD)
print(arrayC.sum())

[[-2 -2 -2]
 [-2 -2 -2]]
21


In [122]:
print(arrayC.sum(axis=0))
print(arrayC.sum(axis=1))
print(arrayC.max(axis=1))
print(arrayC.min(axis=1))

[5 7 9]
[ 6 15]
[3 6]
[1 4]


## transposing

In [123]:
arrayC=np.array([[1,2,3], [4,5,6]])
print(arrayC)
print(arrayC.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [125]:
print(arrayC.T)
print(arrayC.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [127]:
arrayE = np.array([[1,2,3,4,5], [4,5,6,7,8], [7,8,9,10,11]])
print(arrayE.T)
print(arrayE.T.shape)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [128]:
np.random.random([3,2])

array([[0.11743288, 0.42216037],
       [0.13570829, 0.75736842],
       [0.16753888, 0.89523679]])

In [131]:
arrRandom = np.random.random([3,2])*100 #akan berubah setiap dirubah
print(arrRandom)

[[62.08337575 16.40427163]
 [80.54252868 32.52672626]
 [68.44867439 54.16938065]]


In [153]:
np.square(9)

81

In [154]:
np.sqrt(9)

3.0

In [158]:
a = np.log(1000000) #logaritma
print(a)

13.815510557964274


In [157]:
np.exp(a) #exponential values

999999.9999999995

## QUIZ PRIMA

In [150]:
lowest = int(input('Please, enter the lowest range value: '))
upper = int(input('Please, enter the upper range value: '))
print('The prime numbers in the range are: ')
for i in range(lowest, upper+1):
    if i == 1:
        continue
    if i == 2 or i == 3 or i == 5 or i ==7:
        print(i)
    if i % 2 !=0:
            if i % 3 !=0:
                 if i % 5 !=0:
                        if i % 7 !=0:
                            print(i)

Please, enter the lowest range value: 1
Please, enter the upper range value: 20
The prime numbers in the range are: 
2
3
5
7
11
13
17
19
