## Descriptive Statistic

>inferensial statistik bisa langsung ambil informasi dari data kalau descriptive cuma menjelaskan datanya.
+ standar deviasi : seberapa besar sebaran data
+ interquartile range : bisa untuk deteksi outlier
* Q2 = Percentile = 50%

In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8,1,2.5,4,28]
x_with_nan = [8,1,2.5,np.nan,4,28] #np.nan untuk nambahin nilai nan ke list
print(x)
print(x_with_nan)

[8, 1, 2.5, 4, 28]
[8, 1, 2.5, nan, 4, 28]


In [3]:
#buat array(y) dan series(z) dari x

y, y_with_nan = np.array(x), np.array(x_with_nan) #array
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan) #array

print(y)
print(z)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [4]:
z_with_nan.isna()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

## CENTRAL TENDENCY

In [5]:
sum(x)

43.5

In [6]:
len(x)

5

In [7]:
mean_x = sum(x)/len(x)
mean_x

8.7

In [8]:
mean_stats = statistics.mean(x)
print(mean_stats)

8.7


In [9]:
mean_np = np.mean(x)
print(mean_np)

8.7


In [10]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [11]:
y.mean() #array

8.7

In [12]:
z.mean() #series

8.7

In [13]:
y_with_nan.mean()

nan

In [14]:
np.mean(y_with_nan)

nan

In [15]:
np.nan*3

nan

In [16]:
np.nanmean(y_with_nan) #get mean without considering NaN values

8.7

In [17]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

## WEIGHTED MEAN

rata-rata dengan menghitung pembobotan

In [18]:
x #ini metrics/list

[8, 1, 2.5, 4, 28]

In [19]:
w = [0.1,0.2,0.3,0.25,0.15] #weightages

#convert jadi array
y,z,w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean) #weightedmean

6.95


In [20]:
np.mean(x) #mean biasa

8.7

In [21]:
#jabaran perhitungan manual weighted mean
wmean_manual = sum(w[i]*x[i] for i in range(len(x)))/sum(w)
print(wmean_manual)

6.95


In [22]:
sum(w)

1.0

## Harmonic Mean

seringnya untuk rata-rata rate

In [23]:
speed = [60,20]
hmean_speed = len(speed)/sum(1/item for item in speed)
hmean_speed

30.0

In [24]:
#library 1
hmean_speed_stats = statistics.harmonic_mean(speed)
hmean_speed_stats

30.0

In [25]:
#library 2
hmean_speed_stats2 = scipy.stats.hmean(speed)
hmean_speed_stats2

30.0

In [26]:
hmean = len(x) / sum(1/item for item in x)
hmean

2.7613412228796843

In [27]:
x

[8, 1, 2.5, 4, 28]

In [28]:
for item in x:
    print(1/item)

0.125
1.0
0.4
0.25
0.03571428571428571


In [29]:
list(1/item for item in x)

[0.125, 1.0, 0.4, 0.25, 0.03571428571428571]

In [30]:
# hmean dengan library

hmean_stats = statistics.harmonic_mean(x)
hmean_stats

2.7613412228796843

perusahaan berdiri tahun 2017

tahun 2017 omset 1000

2018 naik 30%

2019 naik 50%

tahun 2020 naik 40%

In [31]:
x = 1000
x*=1.3
x*=1.5
x*=1.4
x

2730.0

In [32]:
#arithmetic mean
(30+40+50)/3

40.0

In [33]:
x = 1000
x*=1.4
x*=1.4
x*=1.4
x

2743.9999999999995

In [34]:
#Geometric Mean
gmean = ((30*40*50)**(1/3))
gmean

39.148676411688626

In [35]:
x = 1000
x*=1.3915
x*=1.3915
x*=1.3915
x

2694.322835875

In [36]:
scipy.stats.gmean([30,40,50])

39.14867641168864

## Median

In [37]:
a = [1,2,4,8,9]
n = len(a)

median = a[2] #data ganjil
median

4

In [38]:
#median pakai numpy
x = [8,1,2.5,4,28]
c =[2,3,4,5]
np.median(x)

4.0

In [39]:
sorted(x)

[1, 2.5, 4, 8, 28]

In [40]:
#cari posisi median
n = len(x)
round(0.5*(n-1)) #membulatkan angka

2

In [41]:
#cari posisi median
n = len([1,2,3,4,5,6,7])
round(0.5*(n-1)) #membulatkan angka

3

In [42]:
def median_function(x):
    n = len(x)
    if n%2 == 1:
        median_ = sorted(x)[round(0.5*(n-1))] #sorted ngurut dari kecil ke besar
    else:
        x_ord, index = sorted(x), round(0.5*n)
        median_ = 0.5*(x_ord[index-1]+x_ord[index])

    return median_

In [43]:
median_function(x)

4

In [44]:
median_function(c)

3.5

## Mode

In [45]:
u = [2,3,2,8,12]

mode_= max((u.count(i),i)for i in set(u))[1]

In [46]:
u.count(2)

2

In [47]:
statistics.mode(u)

2

In [48]:
set([1,1,1,2,3,4,5]) #yang redundant dihitung sekali

{1, 2, 3, 4, 5}

In [49]:
mode_lib = scipy.stats.mode(u)

In [50]:
scipy.stats.mode(u)[0]

array([2])

In [51]:
scipy.stats.mode(u)[0][0]

2

In [52]:
print(mode_lib)
print(mode_lib.mode)
print(mode_lib.count)

ModeResult(mode=array([2]), count=array([2]))
[2]
[2]


In [53]:
u

[2, 3, 2, 8, 12]

In [54]:
u_series = pd.Series(u)
u_series.mode()

0    2
dtype: int64

In [55]:
u_array = np.array(u)
statistics.mode(u_array)

2

In [56]:
v = pd.Series([1,2,3,3,3,np.nan])
v.mode()

0    3.0
dtype: float64

In [57]:
statistics.mode(v)

3.0

In [58]:
vv = [1,2,3,3,3,np.nan]
statistics.mode(vv)

3

series mengabaikan nan, array mempertimbangkan nan

## Measure of Variability

In [59]:
x

[8, 1, 2.5, 4, 28]

In [60]:
n = len(x)
mean_var = np.mean(x)
var_ = sum((item-mean_var)**2 for item in x )/(n-1)
var_

123.19999999999999

In [61]:
# using library
var_stat = statistics.variance(x)
var_stat

123.2

In [62]:
# using numpy
var_np = np.var(x, ddof=1) #ddof biar digunain rumus sample variance(n-1)
var_np

123.19999999999999

In [63]:
# variance using series function
z = pd.Series(x)
z.var()

123.19999999999999

## Standar Deviasi

pangkat dari varians

In [64]:
x = [1,2,3,6,7,8,30,40,50]
var_x = np.var(x, ddof=1)
std_x = np.std(x, ddof=1)
print(var_x)
print(std_x)

345.25000000000006
18.58090417606205


In [65]:
#jawaban tim 4
x = [1,2,3,6,7,8,30,40,50]
n = len(x)
mean = sum(x)/n
var_ = sum((item - mean)**2 for item in x)/(n-1)
Sd_ = var_**(1/2)

print(var_)
print(Sd_)

345.25000000000006
18.58090417606205


## Skewness

In [66]:
x = [8,1,2.5,4,28]
n = len(x)
mean = np.mean(x)
stdev = statistics.stdev(x)
skew_ = sum((item - mean)**3 for item in x)*n/((n-1)*(n-2)*(stdev**3))
skew_

1.947043227390592

In [67]:
scipy.stats.skew(x,bias=False)

1.9470432273905927

In [68]:
z = pd.Series(x)
z.skew()

1.9470432273905924

In [69]:
x_with_nan

[8, 1, 2.5, nan, 4, 28]

In [70]:
scipy.stats.skew(x_with_nan)

nan

In [71]:
z_wt_nan = pd.Series(x_with_nan) # series mengabaikan nan
z_wt_nan.skew()

1.9470432273905924

In [72]:
scipy.stats.skew(z_wt_nan)

nan

## Percentiles

In [73]:
x = [-5,-1.1,0.1,2,8,12.8,21,25.8,41]
np.percentile(x,5) #percentile 5

-3.44

In [74]:
np.percentile(x,100) #percentile membagi data menjadi 100

41.0

In [75]:
np.percentile(x,0)

-5.0

In [76]:
statistics.quantiles(x,n=2)

[8.0]

In [77]:
#quartile n =4 membagi data menjadi 4 baagian
statistics.quantiles(x,n=4) 

[-0.5, 8.0, 23.4]

In [78]:
statistics.quantiles(x,n=4, method = 'inclusive') #inclusive akan mempertimbangkan data sebagai batas(output)

[0.1, 8.0, 21.0]

In [79]:
np.quantile(x,1)

41.0

In [80]:
np.quantile(x,0)

-5.0

In [81]:
np.quantile(x,0.5)

8.0

In [82]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [83]:
x_wt_nan = [-5, -1.1,np.nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]
x_wt_nan

[-5, -1.1, nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [84]:
np.quantile(x_wt_nan,0)

nan

In [85]:
np.nanquantile(x_wt_nan,0)

-5.0

In [86]:
np.nanquantile(x_wt_nan,0.5)

8.0

In [87]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [88]:
np.quantile(x, [0.25,0.5,0.75])

array([ 0.1,  8. , 21. ])

In [89]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

## Ranges (max-min)

In [90]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [91]:
# np.ptp untuk hitung range
np.ptp(x)

46.0

In [92]:
np.amax(x)

41.0

In [93]:
np.amin(x)

-5.0

In [94]:
np.amax(x)-np.amin(x)

46.0

## Interquartile Range(Q3-Q1)

biasanya untuk deteksi pencilan

In [95]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [96]:
quartiles = np.quantile(x,[0.25,0.75])
IQR = quartiles[1]-quartiles[0]
IQR

20.9

## Summary of Desc. Stats

In [97]:
result = scipy.stats.describe(x,ddof=1,bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [98]:
result.variance

228.75194444444446

In [99]:
(result.variance)**(1/2) #untuk cari stdev

15.12454774346805

In [100]:
result.minmax[1]-result.minmax[0] #range

46.0

In [101]:
result.skewness

0.9249043136685094

In [102]:
z = pd.Series(x)
z

0    -5.0
1    -1.1
2     0.1
3     2.0
4     8.0
5    12.8
6    21.0
7    25.8
8    41.0
dtype: float64

In [103]:
z.describe()

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

## Correlation (hubungan antar variable)

In [104]:
x = list(range(-10,11))
y = [0,2,2,2,2,3,3,6,7,4,7,6,6,9,4,5,5,10,11,12,14]

x_ar, y_ar = np.array(x), np.array(y)
x_s, y_s = pd.Series(x), pd.Series(y)

In [105]:
len(x)==len(y)

True

### Covariance

In [106]:
n = len(x)

mean_x = np.mean(x)
mean_y = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y)for item in range(n)))/(n-1)
cov_xy

19.95

In [107]:
cov_matrix = np.cov(x,y)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [108]:
np.var(x,ddof=1)

38.5

In [109]:
np.var(y,ddof=1)

13.914285714285711

In [110]:
cov_xy = cov_matrix[0,1] #[0,1] baris 0 kolom 1
cov_xy

19.95

### Correlation Coefficient

ukuran hubungan antar variable

In [111]:
var_x = np.var(x,ddof=1)
var_y = np.var(y,ddof=1)
std_x = var_x**(1/2)
std_y = var_y**(1/2)
r = cov_xy / (std_x*std_y)
r

0.861950005631606

korelasi positif sangat kuat karena sangat mendekati satu.

In [114]:
scipy.stats.pearsonr(x,y)

(0.8619500056316061, 5.122760847201135e-07)

In [112]:
r, p = scipy.stats.pearsonr(x,y)
r

0.8619500056316061

In [113]:
p

5.122760847201135e-07

#### 25 Maret 2023

In [115]:
corr_matrix = np.corrcoef(x,y)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [116]:
scipy.stats.linregress(x,y)

LinregressResult(slope=0.5181818181818181, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [117]:
scipy.stats.linregress(x,y).rvalue

0.861950005631606

#### Pada Array

In [119]:
a = np.array([[1,1,1],
             [2,3,1],
             [4,9,2],
             [8,27,4],
             [16,1,1]])

In [120]:
np.mean(a)

5.4

In [121]:
np.median(a)

2.0

In [125]:
np.mean(a, axis = 0) #vertical

array([6.2, 8.2, 1.8])

In [126]:
np.mean(a, axis=1) #horizontal

array([ 1.,  2.,  5., 13.,  6.])

In [127]:
np.var(a, ddof=1)

53.40000000000001

In [128]:
np.var(a, ddof=1, axis=0)

array([ 37.2, 121.2,   1.7])

#### Pada Dataframe

In [130]:
row_names = ['first','second','third','fourth','fifth']
col_names=['A','B','C']
df = pd.DataFrame(a,index=row_names,columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [131]:
np.mean(df.A)

6.2

In [133]:
df['A'].mean()

6.2

In [135]:
np.var(df, ddof=1)

A     37.2
B    121.2
C      1.7
dtype: float64

In [136]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [137]:
df.mean(axis=0)

A    6.2
B    8.2
C    1.8
dtype: float64